Starlette import version Upgraded  to work with FastAPI correctly
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastapi 0.136.1 requires starlette>=0.46.0, but you have starlette 0.37.2 which is incompatible.